Repository fluent/fluent-bit-docs, pull requests merged in 2021-12, with the labels that each got.

#601 Adds troubleshooting for Roles for AKS clusters
  pipeline/filters/kubernetes.md
Labels: waiting-for-user

#638 Fix typo in section name
  pipeline/inputs/syslog.md
Labels: waiting-for-user

#581 Very minor grammar correction
  installation/sources/build-and-install.md
Labels: waiting-for-user

#436 filter/lua: Document record split and many minor improvements
  pipeline/filters/lua.md
Labels: waiting-for-user

#577 Added documentation for the DNS mode switch and prometheus remote write
  administration/configuring-fluent-bit/configuration-file.md
  administration/networking.md
Labels: waiting-for-user, dco

#629 out_stackdriver: add document of special value `trace`
  pipeline/outputs/stackdriver.md
  pipeline/outputs/stackdriver_special_fields.md
Labels: waiting-for-user, conflict
