Repository fluent/fluent-bit-docs, pull requests merged in 2022-09, with the labels that each got.

#879 pipeline: outputs: observe: fix code block surrounding configuration file
  pipeline/outputs/observe.md
Labels: backport to 1.9.x

#865 pipeline: inputs: nginx: add default values and nginx_plus
  pipeline/inputs/nginx.md
Labels: backport to 1.9.x

#887 Azure Data Explorer docs leftovers
  .gitbook.yaml
  SUMMARY.md
  administration/configuring-fluent-bit/README.md
  installation/sources/build-and-install.md
Labels: 2.0

#824 out_es: Document how to enable payload compress
  pipeline/outputs/elasticsearch.md
Labels: waiting-for-user

#873 out_stackdriver: fix resource labels validation URL
  pipeline/outputs/stackdriver.md
Labels: backport to 1.9.x

#881 exec_wasi: wasm: Add documents for Wasm based plugins
  SUMMARY.md
  pipeline/filters/wasm.md
  pipeline/inputs/exec_wasi.md
Labels: 2.0

#886 golang-output-plugin: add configuration file section
  development/golang-output-plugins.md
Labels: 2.0
