Repository fluent/fluent-bit-docs, pull requests merged in 2022-08, with the labels that each got.

#856 monitoring: add detailed descriptions for each metric
  administration/monitoring.md
Labels: waiting-for-user

#649 filter_kubernetes: add option kube_token_ttl
  pipeline/filters/kubernetes.md
Labels: waiting-on-code-merge

#689 out_forward: add 'unix_path' property
  pipeline/outputs/forward.md
Labels: conflict, waiting-on-code-merge

#830 out_stackdriver: add docs for resource_labels
  pipeline/outputs/stackdriver.md
Labels: 2.0

#841 Azure Kusto Output Plugin Docs
  pipeline/outputs/azure_kusto.md
Labels: 2.0

#845 pipeline: inputs: kmsg: add prio_level option
  pipeline/inputs/kernel-logs.md
Labels: 2.0

#861 configuration-file: add json.convert_nan_to_null
  administration/configuring-fluent-bit/classic-mode/configuration-file.md
  administration/configuring-fluent-bit/yaml/configuration-file.md
Labels: 2.0
