Repository fluent/fluent-bit-docs, pull requests merged in 2022-10, with the labels that each got.

#927 linux: add AL 2022 as a supported platform
  installation/linux/amazon-linux.md
  installation/requirements.md
  installation/supported-platforms.md
Labels: waiting-on-code-merge

#838 in_dummy: add documentation for new copies parameter.
  pipeline/inputs/dummy.md
Labels: dco, waiting-on-code-merge

#925 filter_ecs: new filter for AWS ECS Metadata
  .gitbook.yaml
  SUMMARY.md
  installation/sources/build-and-install.md
  pipeline/filters/ecs-metadata.md
Labels: waiting-on-code-merge

#872 pipeline: inputs: opentelemetry: add docs
  pipeline/inputs/opentelemetry.md
Labels: waiting-for-user, waiting-on-code-merge
