Repository fluent/fluent-bit-docs, pull requests merged in 2022-01, with the labels that each got.

#658 administration: document lowercase HTTP proxy environment variables
  administration/http-proxy.md
  pipeline/outputs/http.md
  pipeline/outputs/prometheus-remote-write.md
Labels: 1.9

#626 Add documentation for the NGINX metrics input plugin.
  pipeline/inputs/nginx.md
Labels: 1.9

#603 feat: write_operation docs
  pipeline/outputs/elasticsearch.md
Labels: 1.9

#565 introduce Apache SkyWalking output plugin docs
  pipeline/outputs/skywalking.md
Labels: 1.9

#523 out_s3: add documentation for Apache Arrow support
  pipeline/outputs/s3.md
Labels: 1.9

#489 Allow insecure/unverified S3 endpoint
  pipeline/outputs/s3.md
Labels: 1.9

#634 out_s3: make option auto_retry_requests default to be true
  pipeline/outputs/cloudwatch.md
  pipeline/outputs/firehose.md
  pipeline/outputs/kinesis.md
  pipeline/outputs/s3.md
Labels: 1.9, conflict

#635 out_file plugin : add option create output directory if does not exist
  pipeline/outputs/file.md
Labels: 1.9, waiting-on-code-merge
