Repository fluent/fluent-bit-docs, pull requests merged in 2023-04, with the labels that each got.

#1026 Log To Metrics Filter Plugin Documentation
  pipeline/filters/log-to-metrics.md
Labels: waiting-on-code-merge

#1067 installation: update for AL2023
  installation/linux/amazon-linux.md
  installation/linux/redhat-centos.md
  installation/linux/ubuntu.md
  installation/supported-platforms.md
Labels: waiting-on-code-merge, 2.1

#1037 in_windows_exporter_metrics: Add parameters and metrics' descriptions
  pipeline/inputs/windows-exporter-metrics.md
Labels: waiting-on-code-merge

#1031 pipeline: filters: grep: add logical_op property
  pipeline/filters/grep.md
Labels: 2.1

#897 filter: aws ec2 tags
  pipeline/filters/aws-metadata.md
Labels: waiting-on-code-merge

#844 pipeline: inputs: podman metrics: Added documentation for in_podman_m…
  SUMMARY.md
  pipeline/inputs/podman-metrics.md
Labels: waiting-on-code-merge

#1070 Add docs for custom headers on http input plugin
  pipeline/inputs/http.md
Labels: 2.1
