Repository fluent/fluent-bit-docs, pull requests merged in 2023-10, with the labels that each got.

#1015 Record accessor limitation
  administration/configuring-fluent-bit/classic-mode/record-accessor.md
  pipeline/filters/ecs-metadata.md
Labels: Stale

#1205 pipeline: filters: lua: add enable_flb_null
  pipeline/filters/lua.md
Labels: backport to 2.1

#1167 filter_log_to_metrics: Add documentation for add_label
  pipeline/filters/log_to_metrics.md
Labels: waiting-for-user, dco
