Repository fluent/fluent-bit-docs, pull requests merged in 2024-01, with the labels that each got.

#1118 input: kafka: Document `data_format` option
  pipeline/inputs/kafka.md
Labels: waiting-on-code-merge

#1264 in_dummy: Add flush_on_startup setting doc.
  pipeline/inputs/dummy.md
Labels: waiting-on-code-merge

#1179 in_winevtlog: Add descriptions about xml query for filtering events
  pipeline/inputs/windows-event-log-winevtlog.md
Labels: 2.1, backport to 2.1

#1184 in_node_exporter_metrics: Add description for processes metrics
  pipeline/inputs/node-exporter-metrics.md
Labels: 2.2
