Repository fluent/fluent-bit-docs, pull requests merged in 2024-02, with the labels that each got.

#1284 out_stackdriver: add k8s_cluster resource type
  pipeline/outputs/stackdriver.md
Labels: waiting-on-code-merge

#1240 typo fix
  pipeline/inputs/elasticsearch.md
Labels: backport to 2.1

#1068 AWS profile attribute documentation for AWS output plugins
  pipeline/outputs/cloudwatch.md
  pipeline/outputs/elasticsearch.md
  pipeline/outputs/firehose.md
  pipeline/outputs/kinesis.md
  pipeline/outputs/opensearch.md
  pipeline/outputs/s3.md
Labels: Stale
