Repository fluent/fluent-bit-docs, pull requests merged in 2024-05, with the labels that each got.

#1311 fix typos
  administration/backpressure.md
  administration/monitoring.md
  development/wasm-filter-plugins.md
  installation/linux/README.md
  pipeline/outputs/splunk.md
  pipeline/outputs/stackdriver.md
  pipeline/outputs/websocket.md
Labels: waiting-for-user, dco, Stale

#1207 pipeline: outputs: loki: Add new `header` options
  pipeline/outputs/loki.md
Labels: waiting-for-user, conflict

#1363 in_prometheus_remote_write: Add documentation for input plugin of prometheus remote write
  SUMMARY.md
  administration/transport-security.md
  pipeline/inputs/prometheus-remote-write.md
Labels: waiting-on-code-merge
