Repository fluent/fluent-bit-docs, pull requests merged in 2025-05, with the labels that each got.

#1546 out_azure_kusto: add docs for plugin buffering functionality
  pipeline/outputs/azure_kusto.md
Labels: waiting-for-user, conflict, waiting-on-code-merge

#1667 administration: add storage.backlog.flush_on_shutfown option
  administration/buffering-and-storage.md
Labels: waiting-on-code-merge

#1574 aws-credentials: update credential page with pod identity information
  administration/aws-credentials.md
Labels: waiting-on-code-merge

#1693 Pipeline: filters: nest: style updates
  pipeline/filters/nest.md
Labels: waiting-for-user

#1685 pipeline: outputs: cloudwatch: Add missing `log_group_class`
  pipeline/outputs/cloudwatch.md
Labels: waiting-for-user
