Repository fluent/fluent-bit-docs, pull requests merged in 2025-06, with the labels that each got.

#1190 Complete the documentation of the legacy mode
  pipeline/filters/grep.md
Labels: Stale

#1079 pipeline: outputs: stackdriver: add http_request_key, clarifications
  pipeline/outputs/stackdriver.md
Labels: waiting-for-user, conflict

#1447 inputs: winevtlog: Adding yaml version of config
  pipeline/inputs/windows-event-log-winevtlog.md
Labels: waiting-for-user, dco, Stale
